# Generated by Django 5.0.3 on 2024-03-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('preparation_steps', models.TextField()),
                ('cooking_time', models.PositiveIntegerField(help_text='время в минутах')),
                ('ingredients', models.TextField()),
                ('images', models.ImageField(blank=True, upload_to='recipe_images/')),
                ('author', models.CharField(max_length=128)),
                ('weight', models.PositiveIntegerField(help_text='вес в граммах')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_webapp.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_webapp.recipe')),
            ],
        ),
    ]
